spring.application.name=bookshelf
spring.datasource.url=jdbc:postgresql://localhost:5432/restapi
spring.datasource.username=root
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgresPlusDialect
spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:init.sql
#spring.sql.init.data-locations=classpath:populate.sql